config/routes.rb
Calc2::Application.routes.draw do
  get "homepage" => "Users#homepage", :as => :homepage
  get "habitfinance" => "Users#habitfinance", :as => :habitfinance

  resources :categories

  resources :rewards

  resources :programs

  resources :cards

  resources :issuers

end

app/models/program.rb
class Program < ActiveRecord::Base
  attr_accessible :card_id, :end_period, :name, :reward_limit, :reward_rate, :start_period

  belongs_to :card
  has_many :rewards 
  has_many :categories, :through => :rewards

  def duration
    (self.end_period.month - self.start_period.month + 1)
  end

  def reward_limit_check
    if self.reward_limit === 0
      self.reward_limit = 10000000000000000000000
    else
      self.reward_limit
    end
  end

  def excess_spend amount
    if amount * self.duration >= reward_limit_check
        ((amount * self.duration) - self.reward_limit) / self.duration
      else 
        0
    end
  end

  def category_rewards amount 
    if amount * self.duration >= reward_limit_check
      self.reward_limit * reward_rate
    else 
      duration * amount * reward_rate
    end
  end 

  def program_details
  	self.categories.map { |category| category.name } 
  end

  def program_hash amount
  	Hash[
  		"Category" => program_details,
  		"Reward Amount" => category_rewards(amount),
      "Excess Rewards" => excess_spend(amount)
  	]
  end

end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
  # GET /programs
  # GET /programs.json
  def index
    @programs = Program.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @programs }
    end
  end

  # GET /programs/1
  # GET /programs/1.json
  def show
    @program = Program.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @program }
    end
  end

  # GET /programs/new
  # GET /programs/new.json
  def new
    @program = Program.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @program }
    end
  end

  # GET /programs/1/edit
  def edit
    @program = Program.find(params[:id])
  end

  # POST /programs
  # POST /programs.json
  def create
    @program = Program.new(params[:program])

    respond_to do |format|
      if @program.save
        format.html { redirect_to new_reward_path, notice: 'Program was successfully created.' }
        format.json { render json: @program, status: :created, location: @program }
      else
        format.html { render action: "new" }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /programs/1
  # PUT /programs/1.json
  def update
    @program = Program.find(params[:id])

    respond_to do |format|
      if @program.update_attributes(params[:program])
        format.html { redirect_to programs_path, notice: 'Program was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /programs/1
  # DELETE /programs/1.json
  def destroy
    @program = Program.find(params[:id])
    @program.destroy

    respond_to do |format|
      format.html { redirect_to programs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/views/programs/_form.html.erb
<%= form_for(@program) do |f| %>
  <% if @program.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@program.errors.count, "error") %> prohibited this program from being saved:</h2>

      <ul>
      <% @program.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :card_id %><br />
    <%= f.collection_select :card_id, Card.all, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :start_period %><br />
    <%= f.date_select :start_period %>
  </div>
  <div class="field">
    <%= f.label :end_period %><br />
    <%= f.date_select :end_period %>
  </div>
  <div class="field">
    <%= f.label :reward_rate %><br />
    <%= f.text_field :reward_rate %>
  </div>
  <div class="field">
    <%= f.label :reward_limit %><br />
    <%= f.number_field :reward_limit %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/programs/edit.html.erb
<h1>Editing program</h1>

<%= render 'form' %>

<%= link_to 'Show', @program %> |
<%= link_to 'Back', programs_path %>

app/views/programs/index.html.erb
<h1>Listing programs</h1>

<table>
  <tr>
    <th>Card</th>
    <th>Name</th>
    <th>Start period</th>
    <th>End period</th>
    <th>Reward rate</th>
    <th>Reward limit</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @programs.each do |program| %>
  <tr>
    <td><%= program.card.name %></td>
    <td><%= program.name %></td>
    <td><%= program.start_period %></td>
    <td><%= program.end_period %></td>
    <td><%= program.reward_rate %></td>
    <td><%= program.reward_limit %></td>
    <td><%= link_to 'Show', program %></td>
    <td><%= link_to 'Edit', edit_program_path(program) %></td>
    <td><%= link_to 'Destroy', program, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Program', new_program_path %>
<%= link_to "Issuers", issuers_path %>
<%= link_to "Cards", cards_path %>
<%= link_to "Rewards", rewards_path %>
<%= link_to "Categories", categories_path %>

app/views/programs/new.html.erb
<h1>New program</h1>

<%= render 'form' %>

<%= link_to 'Back', programs_path %>

app/views/programs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Card:</b>
  <%= @program.card_id %>
</p>

<p>
  <b>Name:</b>
  <%= @program.name %>
</p>

<p>
  <b>Start period:</b>
  <%= @program.start_period %>
</p>

<p>
  <b>End period:</b>
  <%= @program.end_period %>
</p>

<p>
  <b>Reward rate:</b>
  <%= @program.reward_rate %>
</p>

<p>
  <b>Reward limit:</b>
  <%= @program.reward_limit %>
</p>


<%= link_to 'Edit', edit_program_path(@program) %> |
<%= link_to 'Back', programs_path %>