config/routes.rb
Calc2::Application.routes.draw do
  get "homepage" => "Users#homepage", :as => :homepage
  get "habitfinance" => "Users#habitfinance", :as => :habitfinance

  resources :categories

  resources :rewards

  resources :programs

  resources :cards

  resources :issuers

end

app/models/reward.rb
class Reward < ActiveRecord::Base
  attr_accessible :category_id, :program_id

  belongs_to :program
  belongs_to :category


end

app/controllers/rewards_controller.rb
class RewardsController < ApplicationController
  # GET /rewards
  # GET /rewards.json
  def index
    @rewards = Reward.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @rewards }
    end
  end

  # GET /rewards/1
  # GET /rewards/1.json
  def show
    @reward = Reward.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @reward }
    end
  end

  # GET /rewards/new
  # GET /rewards/new.json
  def new
    @reward = Reward.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @reward }
    end
  end

  # GET /rewards/1/edit
  def edit
    @reward = Reward.find(params[:id])
  end

  # POST /rewards
  # POST /rewards.json
  def create
    @reward = Reward.new(params[:reward])

    respond_to do |format|
      if @reward.save
        format.html { redirect_to rewards_path, notice: 'Reward was successfully created.' }
        format.json { render json: @reward, status: :created, location: @reward }
      else
        format.html { render action: "new" }
        format.json { render json: @reward.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /rewards/1
  # PUT /rewards/1.json
  def update
    @reward = Reward.find(params[:id])

    respond_to do |format|
      if @reward.update_attributes(params[:reward])
        format.html { redirect_to rewards_path, notice: 'Reward was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @reward.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rewards/1
  # DELETE /rewards/1.json
  def destroy
    @reward = Reward.find(params[:id])
    @reward.destroy

    respond_to do |format|
      format.html { redirect_to rewards_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/rewards_helper.rb
module RewardsHelper
end

app/views/rewards/_form.html.erb
<%= form_for(@reward) do |f| %>
  <% if @reward.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reward.errors.count, "error") %> prohibited this reward from being saved:</h2>

      <ul>
      <% @reward.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :program_id %><br />
    <%= f.collection_select :program_id, Program.all, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br />
    <%= f.collection_select :category_id, Category.all, :id, :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rewards/edit.html.erb
<h1>Editing reward</h1>

<%= render 'form' %>

<%= link_to 'Show', @reward %> |
<%= link_to 'Back', rewards_path %>

app/views/rewards/index.html.erb
<h1>Listing rewards</h1>

<table>
  <tr>
    <th>Program</th>
    <th>Category</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @rewards.each do |reward| %>
  <tr>
    <td><%= reward.program.name %></td>
    <td><%= reward.category.name %></td>
    <td><%= link_to 'Show', reward %></td>
    <td><%= link_to 'Edit', edit_reward_path(reward) %></td>
    <td><%= link_to 'Destroy', reward, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Reward', new_reward_path %>
<%= link_to "Issuers", issuers_path %>
<%= link_to "Cards", cards_path %>
<%= link_to "Programs", programs_path %>
<%= link_to "Categories", categories_path %>

app/views/rewards/new.html.erb
<h1>New reward</h1>

<%= render 'form' %>

<%= link_to 'Back', rewards_path %>

app/views/rewards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Program:</b>
  <%= @reward.program_id %>
</p>

<p>
  <b>Category:</b>
  <%= @reward.category_id %>
</p>


<%= link_to 'Edit', edit_reward_path(@reward) %> |
<%= link_to 'Back', rewards_path %>