config/routes.rb
Calc2::Application.routes.draw do
  get "homepage" => "Users#homepage", :as => :homepage
  get "habitfinance" => "Users#habitfinance", :as => :habitfinance

  resources :categories

  resources :rewards

  resources :programs

  resources :cards

  resources :issuers

end

app/models/card.rb
class Card < ActiveRecord::Base
  attr_accessible :general_rate, :issuer_id, :name, :rewards_type, :threshold_amount, :threshold_rate

	belongs_to :issuer
	has_many :programs

	def annual_spend amount 
		amount * 12
	end

	def general_rewards amount
		if annual_spend(amount) <= self.threshold_amount
			annual_spend(amount) * self.threshold_rate
		else
				(self.threshold_amount * self.threshold_rate) + ((annual_spend(amount) - self.threshold_amount) * self.general_rate)
		end
	end

	# def program_details amount 
	# 	self.programs.map { |program| program.program_hash(amount) } 
	# end

	# def card_details general_amount, program_amount
	# 		Hash["Name" => self.name,
	# 		"Rewards Type" => self.rewards_type,
	# 		"General Rewards" => general_rewards(general_amount),
	# 		"Program" => self.program_details(program_amount)
	# 	] 
	# end
	def card_details general_amount
			Hash["Name" => self.name,
			"Rewards Type" => self.rewards_type,
			"General Rewards" => general_rewards(general_amount),
		] 
	end


end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  # GET /cards
  # GET /cards.json
  def index
    @cards = Card.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cards }
    end
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
    @card = Card.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @card }
    end
  end

  # GET /cards/new
  # GET /cards/new.json
  def new
    @card = Card.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @card }
    end
  end

  # GET /cards/1/edit
  def edit
    @card = Card.find(params[:id])
  end

  # POST /cards
  # POST /cards.json
  def create
    @card = Card.new(params[:card])

    respond_to do |format|
      if @card.save
        format.html { redirect_to cards_path, notice: 'Card was successfully created.' }
        format.json { render json: @card, status: :created, location: @card }
      else
        format.html { render action: "new" }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cards/1
  # PUT /cards/1.json
  def update
    @card = Card.find(params[:id])

    respond_to do |format|
      if @card.update_attributes(params[:card])
        format.html { redirect_to cards_path, notice: 'Card was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card = Card.find(params[:id])
    @card.destroy

    respond_to do |format|
      format.html { redirect_to cards_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/_form.html.erb
<%= form_for(@card) do |f| %>
  <% if @card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
      <% @card.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :issuer_id %><br />
    <%= f.collection_select :issuer_id, Issuer.all, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :rewards_type %><br />
    <%= f.text_field :rewards_type %>
  </div>
  <div class="field">
    <%= f.label :general_rate %><br />
    <%= f.text_field :general_rate %>
  </div>
  <div class="field">
    <%= f.label :threshold_amount %><br />
    <%= f.number_field :threshold_amount %>
  </div>
  <div class="field">
    <%= f.label :threshold_rate %><br />
    <%= f.text_field :threshold_rate %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cards/edit.html.erb
<h1>Editing card</h1>

<%= render 'form' %>

<%= link_to 'Show', @card %> |
<%= link_to 'Back', cards_path %>

app/views/cards/index.html.erb
<h1>Listing cards</h1>

<table>
  <tr>
    <th>Issuer</th>
    <th>Name</th>
    <th>Rewards type</th>
    <th>General rate</th>
    <th>Threshold amount</th>
    <th>Threshold rate</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @cards.each do |card| %>
  <tr>
    <td><%= card.issuer.name %></td>
    <td><%= card.name %></td>
    <td><%= card.rewards_type %></td>
    <td><%= card.general_rate %></td>
    <td><%= card.threshold_amount %></td>
    <td><%= card.threshold_rate %></td>
    <td><%= link_to 'Show', card %></td>
    <td><%= link_to 'Edit', edit_card_path(card) %></td>
    <td><%= link_to 'Destroy', card, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Card', new_card_path %>
<%= link_to "Issuers", issuers_path %>
<%= link_to "Programs", programs_path %>
<%= link_to "Rewards", rewards_path %>
<%= link_to "Categories", categories_path %>
</br>

<%= form_tag homepage_path, :method => "get" do %>
</br>
 <script>
    $(function() {
        $( "#accordion" ).accordion();
    });
    </script>
<div id="accordion">
    <h3>Section 1</h3>
    <div>
General Spend: <%= number_field_tag :general_spend, @general_spend %></br>
Gas: <%= number_field_tag :gas, @gas %></br>
Movies: <%= number_field_tag :movies, @movies %></br>
Groceries: <%= number_field_tag :groceries, @groceries %></br>
Travel: <%= number_field_tag :travel, @travel %> </br>
Museums: <%= number_field_tag :museums, @museums %></br>
    </div>
    <h3>Section 2</h3>
    <div>
Theme Parks: <%= number_field_tag :theme_parks, @theme_parks %></br>
Restaurants: <%= number_field_tag :restaurants, @restaurants %></br>
Airlines: <%= number_field_tag :airlines, @airlines %>
Delta: <%= number_field_tag :delta, @delta %>
Department Stores: <%= number_field_tag :department_stores, @department_stores %></br>
Travel: <%= number_field_tag :travel, @travel %>
    </div>
<%= submit_tag "Submit", :name => nil   %>
<% end %>

app/views/cards/new.html.erb
<h1>New card</h1>

<%= render 'form' %>

<%= link_to 'Back', cards_path %>

app/views/cards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Issuer:</b>
  <%= @card.issuer_id %>
</p>

<p>
  <b>Name:</b>
  <%= @card.name %>
</p>

<p>
  <b>Rewards type:</b>
  <%= @card.rewards_type %>
</p>

<p>
  <b>General rate:</b>
  <%= @card.general_rate %>
</p>

<p>
  <b>Threshold amount:</b>
  <%= @card.threshold_amount %>
</p>

<p>
  <b>Threshold rate:</b>
  <%= @card.threshold_rate %>
</p>


<%= link_to 'Edit', edit_card_path(@card) %> |
<%= link_to 'Back', cards_path %>